INSERT INTO `cis_tce_dsce`.`program_outcomes` (`po_description`) VALUES ('Engineering knowledge: Apply the knowledge of mathematics, science, engineering fundamentals, and an engineering specialization to the solution of complex engineering problems');
INSERT INTO `cis_tce_dsce`.`program_outcomes` (`po_description`) VALUES ('Problem analysis: Identify, formulate, review research literature, and analyze complex engineering problems reaching substantiated conclusions using first principles of mathematics, natural sciences, and engineering sciences');
INSERT INTO `cis_tce_dsce`.`program_outcomes` (`po_description`) VALUES ('Design/development of solutions: Design solutions for complex engineering problems and design system components or processes that meet the specified needs with appropriate consideration for the public health and safety, and the cultural, societal, and environmental considerations');
INSERT INTO `cis_tce_dsce`.`program_outcomes` (`po_description`) VALUES ('Conduct investigations of complex problems: Use research-based knowledge and research methods including design of experiments, analysis and interpretation of data, and synthesis of the information to provide valid conclusions');
INSERT INTO `cis_tce_dsce`.`program_outcomes` (`po_description`) VALUES ('Modern tool usage: Create, select, and apply appropriate techniques, resources, and modern engineering and IT tools including prediction and modeling to complex engineering activities with an understanding of the limitations');
INSERT INTO `cis_tce_dsce`.`program_outcomes` (`po_description`) VALUES ('The engineer and society: Apply reasoning informed by the contextual knowledge to assess societal, health, safety, legal and cultural issues and the consequent responsibilities relevant to the professional engineering practice');
INSERT INTO `cis_tce_dsce`.`program_outcomes` (`po_description`) VALUES ('Environment and sustainability: Understand the impact of the professional engineering solutions in societal and environmental contexts, and demonstrate the knowledge of, and need for sustainable development');
INSERT INTO `cis_tce_dsce`.`program_outcomes` (`po_description`) VALUES ('Ethics: Apply ethical principles and commit to professional ethics and responsibilities and norms of the engineering practice');
INSERT INTO `cis_tce_dsce`.`program_outcomes` (`po_description`) VALUES ('Individual and team work: Function effectively as an individual, and as a member or leader in diverse teams, and in multidisciplinary settings');
INSERT INTO `cis_tce_dsce`.`program_outcomes` (`po_description`) VALUES ('Communication: Communicate effectively on complex engineering activities with the engineering community and with society at large, such as, being able to comprehend and write effective reports and design documentation, make effective presentations, and give and receive clear instructions');
INSERT INTO `cis_tce_dsce`.`program_outcomes` (`po_description`) VALUES ('Project management and finance: Demonstrate knowledge and understanding of the engineering and management principles and apply these to one’s own work, as a member and leader in a team, to manage projects and in multidisciplinary environments');
INSERT INTO `cis_tce_dsce`.`program_outcomes` (`po_description`) VALUES ('Life-long learning: Recognize the need for, and have the preparation and ability to engage in independent and life-long learning in the broadest context of technological change');

INSERT INTO `cis_tce_dsce`.`companies`(`Company`)VALUES('Mu Sigma');
INSERT INTO `cis_tce_dsce`.`companies`(`Company`)VALUES('Infosys');
INSERT INTO `cis_tce_dsce`.`companies`(`Company`)VALUES('Accenture');
INSERT INTO `cis_tce_dsce`.`companies`(`Company`)VALUES('CTS');
INSERT INTO `cis_tce_dsce`.`companies`(`Company`)VALUES('Tech Mahindra');
INSERT INTO `cis_tce_dsce`.`companies`(`Company`)VALUES('L&T InfoTech');
INSERT INTO `cis_tce_dsce`.`companies`(`Company`)VALUES('MICROLAND');
INSERT INTO `cis_tce_dsce`.`companies`(`Company`)VALUES('HP');
INSERT INTO `cis_tce_dsce`.`companies`(`Company`)VALUES('CAPGEMINI');
INSERT INTO `cis_tce_dsce`.`companies`(`Company`)VALUES('CGI');